apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm516-classificacao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classificacao
  template:
    metadata:
      labels:
        app: classificacao
    spec:
      containers:
        - name: classificacao
          image: lucaspaga/classificacao
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ecm516-classificacao-clusterip-service
spec:
  selector:
    app: classificacao
  ports:
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000

