apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm516-consulta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulta
  template:
    metadata:
      labels:
        app: consulta
    spec:
      containers:
        - name: consulta
          image: lucaspaga/consulta
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ecm516-consulta-clusterip-service
spec:
  selector:
    app: consulta
  ports:
    - name: consulta
      protocol: TCP
      port: 6000
      targetPort: 6000

