apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm516-observacoes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observacoes
  template:
    metadata:
      labels:
        app: observacoes
    spec:
      containers:
        - name: observacoes
          image: lucaspaga/observacoes
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ecm516-observacoes-clusterip-service
spec:
  selector:
    app: observacoes
  ports:
    - name: observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000

